강지원 백엔드 과제 제출 합니다.
insertcourse/soccer-game-middle pull request #2
Opened 2023-05-24 04:13 UTC by J1W0N-1209

세상에 나와서는 안 될 코드를 작성했습니다 ..

2023-05-24 10:53 UTC, qlido commented on README.md
> +5. 승자 판단 로직 구현
체크 박스를 사용하면 더 좋을것 같습니다! 

- [ ] 할일 1

2023-05-24 10:53 UTC, qlido commented on src/main/java/Player.java
> +        this.score = 0;
```int score = 0``` 으로 처리해도 되고 초기 값을 주지 않아도 자동으로 0으로 처리 됩니다. 
알고만 계세요

2023-05-24 10:53 UTC, qlido commented on src/main/java/SoccerGameApplication.java
> +        boolean isGameOver = true;
isGameOver는 게임이 오버되었는가로 읽힐 가능성이 많습니다.
isPlayingGame 정도로 바꾸면 좋겠네요

2023-05-24 11:17 UTC, qlido requested changes

2023-05-24 11:17 UTC, qlido commented on src/main/java/SoccerGameApplication.java
> +        String[] goalkeepers = getPlayers(scanner,"골키퍼");
List<Player>로 사용했으면 어땠을까요?

2023-05-24 11:17 UTC, qlido commented on src/main/java/SoccerGameApplication.java
> +            isGameOver = (ContainMatchPoint(players,scores,matchPoint) == null ? true : false );
이것과 if문과 다를 점이 뭘까요?

2023-05-24 11:17 UTC, qlido commented on src/main/java/SoccerGameApplication.java
> +            printResult(players[3],new Goalkeeper(players[4].getName()));
왜 항상 새로운 객체를 생성하나요?

2023-05-24 11:17 UTC, qlido commented on src/main/java/SoccerGameApplication.java
> +        }
로직을 단순화 할 방법을 생각해보세요

2023-05-26 00:49 UTC, J1W0N-1209 commented
수정했습니다.

2023-05-27 11:10 UTC, qlido commented on src/main/java/SoccerGameApplication.java
전체적으로 이 Application이라는 크래스가 모든 책임을 담당하고 있어요
분리해보시는게 어떨까요?

2023-05-27 11:10 UTC, qlido commented on src/main/java/SoccerGameApplication.java
> +        Midfielder midfielder2 = new Midfielder(midfielders.get(1));
List<Player>로 선선해서 한번에 관리하는게 좋을것 같아요

2023-05-27 11:10 UTC, qlido commented on src/main/java/SoccerGameApplication.java
> +            count ++;
이런 로직도 반복으로 처리할 수 있을 것 같습니다

2023-05-27 11:10 UTC, qlido commented on src/main/java/Goalkeeper.java
> +        return true;
여기 있는 로직이 너무 과도한 조건이라고 생각이 듭니다

2023-05-27 11:10 UTC, qlido commented on src/main/java/Midfielder.java
> +        int shoot = random.nextInt(11); // 0 ~ 11
0~10 입니다 주석이 잘못되었네요

2023-05-31 11:13 UTC, J1W0N-1209 commented
수정했습니다

2023-08-23 13:50 UTC, closed without merging